version: '3.8'
volumes:
  data:
services: 
  dockercompose:
    build: ./dir
    image: webservice
    ports: 
      - "3306:80"
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
    ports:
      - "3030:3030"
  app:
    image: phpmyadmin/phpmyadmin:latest
    links: 
      - db
    ports: 
      - "3000:80"
    environment:
      - PMA_ARBITRARY=1
  