version: '3.8'
volumes:
  data:
services: 
  dockercompose:
    build: ./dir
    image: webservice
    ports: 
      - "3030:80"
    links:
    - db
    - app
  db:
    image: mysql:8.0
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development 
    ports:
      - "3306:80"
  app:
    image: phpmyadmin/phpmyadmin:latest
    links: 
      - db
    ports: 
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
  